# def get_digit(number, position):
#     """return digit at position in number,counting from right
#
#
#
#     """
#     # assert 4 == 2, " 4 is not equal to 2"
#     return number//(10**position) % 10
# print(get_digit(23568789,3))


# def get_digit(number: int, position: int) -> int:
#     """return digit at position in number,counting from right
#     >>> get_digit(234,0)
#     4
#     >>> get_digit(234,2)
#     2
#     >>> 3== 4
#     False
#     >>> "hello"
#     'hello'
#      >>> '2' + 3 # doctest: +IGNORE_EXCEPTION_DETAIL
#      Traceback (most recent call last):
#         ...
#      TypeError:
#
#
#
#
#
#
#     """
#     # assert 4 == 2, " 4 is not equal to 2"
#     return number // (10 ** position) % 10
#
#
# # print(get_digit(234, 2))
